### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by jianhaizhang** [BaselAbujamous/clust#45]
Hi,

I cloned your git repository and cd to "clust/ExampleData/1_RawData", then run "clust Data/ -r Replicates.txt -n Normalisation.txt -m MapIDs.txt". It gives the following errors:

Traceback (most recent call last):
  File "/rhome/jzhan067/.local/bin/clust", line 7, in <module>
    from clust.__main__ import main
  File "/rhome/jzhan067/.local/lib/python2.7/site-packages/clust/__init__.py", line 1, in <module>
    from .clustpipeline import runclust
  File "/rhome/jzhan067/.local/lib/python2.7/site-packages/clust/clustpipeline.py", line 1, in <module>
    import matplotlib
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda2/4.4.10/lib/python2.7/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/opt/linux/centos/7.x/x86_64/pkgs/miniconda2/4.4.10/lib/python2.7/site-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
ImportError: No module named numpy

How to resolve it?

Regards.

**Comment by jianhaizhang** [comment]
The error came from "numpy". Resolved!

**Comment by BaselAbujamous** [comment]
Great to hear it has been resolved!! Can we close the issue now? I will close it. Please feel free to reopen it if you like or to report any new issues.
