### ISSUE TITLE
Clust 1.10.7 incompatibility issue with Pandas 0.25.0 

### ISSUE THREAD

**Issue by adriayumi** [BaselAbujamous/clust#48]
Hi,
I have just installed clust using anaconda and I am trying to run it but I keep getting the same error, even when I try to run your examples. I also tried to run with your example data on the clust's Beta website, which also gives an unespecified error. Below is the error message on my terminal:
```
/===========================================================================\
|                                   Clust                                   |
|    (Optimised consensus clustering of multiple heterogenous datasets)     |
|           Python package version 1.10.7 (2019) Basel Abu-Jamous           |
+---------------------------------------------------------------------------+
| Analysis started at: Thursday 08 August 2019 (23:44:55)                   |
| 1. Reading dataset(s)                                                     |
Traceback (most recent call last):
  File "/home/adriayumi/miniconda3/bin/clust", line 12, in <module>
    sys.exit(main())
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/clust/__main__.py", line 103, in main
    args.cs, args.np, args.optimisation, args.q3s, args.basemethods, args.deterministic)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/clust/clustpipeline.py", line 86, in clustpipeline
    returnSkipped=True)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 46, in readDatasetsFromDirectory
    datafilesread = readDataFromFiles(datafileswithpath, delimiter, float, skiprows, skipcolumns, returnSkipped)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 205, in readDataFromFiles
    usecols=range(skipcolumns, ncols), na_filter=data_na_filter, comments=comm)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 240, in pdreadcsv_regexdelim
    delimiter='\t', dtype=dtype, header=-1, skiprows=skiprows, usecols=usecols, na_filter=na_filter, comment=comments).values
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/adriayumi/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1906, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 534, in pandas._libs.parsers.TextReader.__cinit__
OverflowError: can't convert negative value to npy_uint64`
```

I noticed that it could be a problem with pandas version 0.25.0. So I run clust under an environment with an older pandas version (0.24.0), and it ran normally. I suggest to add this to the requirements.

**Comment by BaselAbujamous** [comment]
Hi and sorry for the late reply. I have updated clust to version 1.10.8 which solves the problem above. Thanks a lot for reporting it.
