### ISSUE TITLE
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

### ISSUE THREAD

**Issue by maxnest** [BaselAbujamous/clust#49]
First of all thanks for this great and useful tool!
Unfortunately, I encountered the following error:

/===========================================================================\
|                                   Clust                                   |
|    (Optimised consensus clustering of multiple heterogenous datasets)     |
|           Python package version 1.10.8 (2019) Basel Abu-Jamous           |
+---------------------------------------------------------------------------+
| Analysis started at: Friday 01 November 2019 (00:46:42)                   |
| 1. Reading dataset(s)                                                     |
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1191, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maxnestlcl/anaconda3/bin/clust", line 12, in <module>
    sys.exit(main())
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/clust/__main__.py", line 103, in main
    args.cs, args.np, args.optimisation, args.q3s, args.basemethods, args.deterministic)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/clust/clustpipeline.py", line 86, in clustpipeline
    returnSkipped=True)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 46, in readDatasetsFromDirectory
    datafilesread = readDataFromFiles(datafileswithpath, delimiter, float, skiprows, skipcolumns, returnSkipped)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 205, in readDataFromFiles
    usecols=range(skipcolumns, ncols), na_filter=data_na_filter, comments=comm)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/clust/scripts/io.py", line 240, in pdreadcsv_regexdelim
    delimiter='\t', dtype=dtype, header=None, skiprows=skiprows, usecols=usecols, na_filter=na_filter, comment=comments).values
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/maxnestlcl/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 991, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1123, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1197, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: could not convert string to float: 'TPA_4h'

Thanks!

**Comment by maxnest** [comment]
Dear authors and colleagues, 
Solution for this problem is quite simple: directory with data must not to contain other files, including the description of the design of the experiment (like in my case: ValueError: could not convert string to float: 'TPA_4h').  Once again thanks you for a great program!

**Comment by BaselAbujamous** [comment]
@maxnest Thanks for using clust, and happy to see the issue resolved.

I hope you get the results you like from the method and best of luck in your research.
Please let me know if other problems appear.

Basel
