### ISSUE TITLE
more_itertools versioning???

### ISSUE THREAD

**Issue by DallasThomas** [BaselAbujamous/clust#56]
Has anyone seen this before?  Looks like versioning issues any thoughts or quick fixes anyone has found?
 
Thanks

```
# clust
Traceback (most recent call last):
  File "/usr/local/falcon/LOCAL/bin/clust", line 7, in <module>
    from clust.__main__ import main
  File "/usr/local/falcon/LOCAL/lib/python2.7/site-packages/clust/__init__.py", line 1, in <module>
    from .clustpipeline import runclust
  File "/usr/local/falcon/LOCAL/lib/python2.7/site-packages/clust/clustpipeline.py", line 3, in <module>
    import clust.scripts.io as io
  File "/usr/local/falcon/LOCAL/lib/python2.7/site-packages/clust/scripts/io.py", line 5, in <module>
    import clust.scripts.numeric as nu
  File "/usr/local/falcon/LOCAL/lib/python2.7/site-packages/clust/scripts/numeric.py", line 4, in <module>
    import sklearn.metrics.pairwise as skdists
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/ranking.py", line 36, in <module>
    from ..preprocessing import label_binarize
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/testing.py", line 751, in <module>
    import pytest
  File "/usr/local/lib/python2.7/dist-packages/pytest.py", line 34, in <module>
    from _pytest.python_api import approx
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python_api.py", line 11, in <module>
    from more_itertools.more import always_iterable
  File "/usr/local/lib/python2.7/dist-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/more_itertools/more.py", line 329
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax
```

**Comment by DallasThomas** [comment]
Never mind - the issue is related to more_itertools not working with python2.7.

Worked around this.
